### PR TITLE
Add script files from atst script/include

### PR DESCRIPTION
**Pull request by ddsdevon**
Initial import of the shared scripts and function include files (pulled from ATST's /script/include directory)

### CODE REVIEW

**Comment by patricksmithdds** [comment]
@ddsdevon Could add some quick docs about how each of these files will interact with the scripts in the other repos? For example, how does `test_functions.inc.sh` and `run_test` relate to `script/test` in another repo?

**Comment by ddsdevon** [comment]
README updated

**Comment by ddsdevon** [comment]
@briandds @patricksmithdds Added documentation/download links; removed pip as a hard requirement.

**Review by patricksmithdds — APPROVED** [review]
Looks good to me 👍 

I think I'm still missing how exactly another ATAT repo will use this repo to include scripts, but I assume that's coming in a later PR.

**Comment by ddsdevon** [comment]
@patricksmithdds Yep! There is actually a branch on ATST I'll be PRing once this is merged... basically, this repo gets pulled into /script/includes as a submodule. Stay tuned!

**Pull request merged**
